---
output:
  pagedown::html_paged:
    toc: false
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: true
    css: ["default-fonts", "../custom_paged.css", "../custom.css"]
paged-footnotes: true
lot: false
lof: false
params:
  year: 2018--19
  survey: Staff Compensation and Demographics Survey
title: '`r sprintf("%s<br>%s<br>", params$year, params$survey)`'
subtitle: "Executive Summary"
---

```{r setup, include=FALSE} 
library(tidyverse)
library(gt) 
knitr::opts_chunk$set(echo = FALSE) 
```

<!-- Add new sections with an H1 header. -->
# Preface {-}
<!-- The {-} tells Markdown to not add a section number. -->

# Tables {-}
<!-- Using gt for tables https://gt.rstudio.com/ -->

```{r}
tbl <- 
  dplyr::tribble(
    ~groupname, ~rowname, ~participants,
    "Asia-Pacific",        "Asia (excluding Middle and Near East)",      76,   
    "Asia-Pacific",        "Oceania",      26,   
    "Europe, Middle East, and Africa (EMEA)",        "Africa",      6,  
    "Europe, Middle East, and Africa (EMEA)",        "Europe and Near East",      136,  
    "Europe, Middle East, and Africa (EMEA)",        "Middle East",      21,  
    "The Americas",        "Canada",      35,
    "The Americas",        "Latin America and Caribbean",      17,
    "The Americas",        "United States",      503,
  )

gt(tbl) %>% 
  summary_rows(
    columns = vars(participants),
    fns = "sum"
  ) %>% 
  tab_footnote(
    footnote = "Excluding Puerto Rico, which is included in the Caribbean numbers",
    locations = cells_stub(
      rows = "United States"
    )
  ) %>% 
  tab_options(
    footnote.glyph = "*", table.width = pct(100)
  )  
```

# Blockquotes {-}
<!-- Starting a line with '>' will add it as a blockquote as in the original executive summaries -->

>Out of all the schools that indicated that they offer at least one bachelor’s degree program, the most common discipline reported was accounting (approximately 71 percent), with management as the second-most common discipline reported (approximately 63 percent).





